### PR TITLE
Fix: do not overwrite default origin language

### LINKED ISSUE #198: If "The language of the origin text" is not specified, tranlation doesn't work
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Open NC assistant
2. Go to *Translate*
3. Enter text to be translated
4. Under *The language of the origin text* DO NOT select any entry.
5. Select language to be translated to

### Expected behaviour
When nothing is specified unter *The language of the origin text*, the default "Detect language" should be automatically active.

### Actual behaviour
When clicking on Translate, the NC assistant is closed and an error message appears on the top right corner: Fehler des Assistenten: [object Object]✖ 

### Server configuration

**Web server:** nginx

**Database:** MariaDB

**PHP version:** 8.3

**Nextcloud version:** 30.0.6

**App version translate2**: 2.0.3

### PR DESCRIPTION
**Pull request by janepie**
resolves #198

### CODE REVIEW

File: src/components/AssistantTextProcessingForm.vue [hunk 1]
```diff
@@ -389,7 +389,9 @@ export default {
 							tt.inputShape.style_input.placeholder = t('assistant', 'Shakespeare or an example of the style')
 							tt.inputShape.source_input.placeholder = t('assistant', 'A description of what you need or some original content')
 						} else if (tt.id === 'core:text2text:translate') {
-							tt.inputShapeDefaults.origin_language = 'detect_language'
+							if (!tt.inputShape.origin_language) {
+								tt.inputShapeDefaults.origin_language = 'detect_language'
```
Comment (marcelklehr) [inline src/components/AssistantTextProcessingForm.vue:393]: I may not be the right person to review this, I don't get why this works :sweat_smile:

**Review by marcelklehr — APPROVED** [review]

**Review by julien-nc — APPROVED** [review]
